spring:
  datasource:
    url: jdbc:mysql://192.168.1.131:3306/boot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root

server:
  port: 8080
  servlet:
    context-path: /
