spring:
  datasource:
    url: jdbc:mysql://192.168.1.131:3306/boot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  #JPA\u914D\u7F6E
  jpa:
    hibernate:
      ddl-auto: update
    #\u8F93\u51FAsql
    show-sql: true
    #\u6570\u636E\u5E93\u7C7B\u578B
    database: mysql
