## 数据库设置
spring:
  datasource:
    url: jdbc:mysql://192.168.5.135:3316/shiro_demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: databank_135
    password: yoYi_2016
  ## redis配置
  redis:
    host: 192.168.5.134
    port: 6379


## 日志配置路径
logging:
  config: classpath:log4j2-dev.xml

## swagger配置
swagger:
  enable: true