## 数据库设置
spring:
  datasource:
    url: jdbc:mysql://192.168.1.131:3306/shiro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: SELECT 1
    filters: stat,log4j,wall,config

  ## redis配置
  redis:
    host: 192.168.1.131
    port: 6379


## 日志配置路径
logging:
  config: classpath:log4j2-dev.xml

## swagger配置
swagger:
  enable: true