## 服务配置
server:
  port: 8080
##  servlet:
##    context-path: /shiro-demo
spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: SELECT 1
    filters: stat,log4j,wall,config
  redis:
    #客户端超时时间单位是毫秒 默认是2000
    timeout: 10000
    lettuce:
      pool:
        #最大空闲数
        max-idle: 8
        #连接池的最大数据库连接数
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        #连接池中的最小空闲连接
        min-idle: 0
      #关闭超时时间
      shutdown-timeout: 100


## mybatis
mybatis:
  type-aliases-package: com.hongfei.springbootshiro.**.model
  type-handlers-package: com.hongfei.springbootshiro.**.mapper
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


## pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  auto-runtime-dialect: true